[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-selenium"
version = "0.1.0"
description = "Python Selenium project"
dependencies = []

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
testpaths = ["tests"]
pythonpath = ["src"]
python_files = "test_*.py"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
